# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
#title: Frederick Vanbrabant delirious rantings
email: frederick.vanbrabant@gmail.com
#description: > # this means to ignore newlines until "baseurl:"
 #  A less then 30 year old developer from Antwerp with a passion for API's and everything that surrounds them. Works as a Software Engineer at madewithlove and is co-organiser of PHPAntwerp
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://frederickvanbrabant.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: theEdonian
twitter:
  username: maybeFrederick
github_username:  vanbrabantf
author: Frederick Vanbrabant
social:
  name: Frederick Vanbrabant
  links:
    - https://twitter.com/TheEdonian
    - https://www.linkedin.com/in/frederickvanbrabant/
    - https://github.com/vanbrabantf
    - https://symposiumapp.com/u/frederick
    - http://www.speakersbase.com/frederick-vanbrabant

# Build settings
markdown: kramdown
theme: minima
highlighter: rouge
paginate: 9
paginate_path: "/page/:num"
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock